"""Train a weakly-supervised lane-marking segmentation model.

This first v18 experiment is intentionally narrow: segment road markings from
satellite RGB images inside the satellite road/impervious mask. Labels are
generated by conservative color/edge rules, so no manual annotation is required.

Classes:
0 background
1 yellow_marking
2 white_marking
"""

from __future__ import annotations

import argparse
import json
import random
import sys
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, List

import cv2
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
import torchvision.transforms.functional as TF
import yaml
from PIL import Image
from torch.utils.data import DataLoader, Dataset
from torchvision.models.segmentation import deeplabv3_mobilenet_v3_large

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

IMAGE_EXTENSIONS = (".jpg", ".jpeg", ".png", ".bmp", ".tif", ".tiff")

PALETTE = np.array(
    [
        [0, 0, 0],        # background
        [255, 220, 0],    # yellow marking
        [255, 255, 255],  # white marking
    ],
    dtype=np.uint8,
)


@dataclass
class Sample:
    image_path: Path
    semantic_path: Path
    sample_id: str


def load_yaml(path: str | Path) -> dict:
    with open(path, "r", encoding="utf-8") as f:
        return yaml.safe_load(f)


def iter_image_files(directory: Path) -> Iterable[Path]:
    for path in sorted(directory.iterdir(), key=lambda p: p.stem):
        if path.is_file() and path.suffix.lower() in IMAGE_EXTENSIONS:
            yield path


def find_label(label_dir: Path, stem: str) -> Path | None:
    for suffix in (".png", ".jpg", ".jpeg", ".bmp"):
        candidate = label_dir / f"{stem}{suffix}"
        if candidate.exists():
            return candidate
    return None


def collect_samples(root: Path, split: str, image_dir: str, semantic_dir: str) -> List[Sample]:
    image_root = root / split / image_dir
    semantic_root = root / split / semantic_dir
    if not image_root.exists():
        raise FileNotFoundError(image_root)
    if not semantic_root.exists():
        raise FileNotFoundError(semantic_root)

    samples: List[Sample] = []
    for image_path in iter_image_files(image_root):
        label_path = find_label(semantic_root, image_path.stem)
        if label_path is None:
            continue
        samples.append(Sample(image_path=image_path, semantic_path=label_path, sample_id=image_path.stem))
    if not samples:
        raise RuntimeError(f"No matched samples found for {split}: {image_root} / {semantic_root}")
    return samples


def read_rgb(path: Path) -> np.ndarray:
    image = cv2.imread(str(path), cv2.IMREAD_COLOR)
    if image is None:
        raise ValueError(f"Failed to read image: {path}")
    return cv2.cvtColor(image, cv2.COLOR_BGR2RGB)


def read_label(path: Path, size_hw: tuple[int, int]) -> np.ndarray:
    label = cv2.imread(str(path), cv2.IMREAD_GRAYSCALE)
    if label is None:
        raise ValueError(f"Failed to read label: {path}")
    if label.shape[:2] != size_hw:
        label = cv2.resize(label, (size_hw[1], size_hw[0]), interpolation=cv2.INTER_NEAREST)
    return label.astype(np.uint8)


def weak_lane_label(rgb: np.ndarray, semantic: np.ndarray, road_label: int = 0) -> np.ndarray:
    """Conservative road-marking pseudo labels from satellite RGB + road mask."""
    h, w = rgb.shape[:2]
    road = semantic == int(road_label)
    if road.sum() < 16:
        return np.zeros((h, w), dtype=np.uint8)

    hsv = cv2.cvtColor(rgb, cv2.COLOR_RGB2HSV)
    hh, ss, vv = hsv[..., 0], hsv[..., 1], hsv[..., 2]
    r = rgb[..., 0].astype(np.int16)
    g = rgb[..., 1].astype(np.int16)
    b = rgb[..., 2].astype(np.int16)
    gray = cv2.cvtColor(rgb, cv2.COLOR_RGB2GRAY)
    local = cv2.absdiff(gray, cv2.GaussianBlur(gray, (13, 13), 0))
    edges = cv2.Canny(cv2.GaussianBlur(gray, (3, 3), 0), 45, 135) > 0
    edges = cv2.dilate(edges.astype(np.uint8), np.ones((2, 2), np.uint8), iterations=1).astype(bool)

    yellow = (
        road
        & (hh >= 12)
        & (hh <= 45)
        & (ss >= 28)
        & (vv >= 70)
        & (r > b + 12)
        & (g > b + 8)
        & ((edges) | (local > 8))
    )
    white = (
        road
        & (ss <= 55)
        & (vv >= 135)
        & ((np.maximum.reduce([r, g, b]) - np.minimum.reduce([r, g, b])) <= 45)
        & ((edges) | (local > 10))
    )

    # Remove broad road shoulders / sand patches; keep thin elongated components.
    label = np.zeros((h, w), dtype=np.uint8)
    for cls_id, mask in ((1, yellow), (2, white)):
        mask_u8 = cv2.morphologyEx(mask.astype(np.uint8), cv2.MORPH_OPEN, np.ones((2, 2), np.uint8))
        num, comps, stats, _ = cv2.connectedComponentsWithStats(mask_u8, connectivity=8)
        for comp_id in range(1, num):
            x, y, bw, bh, area = stats[comp_id]
            if area < 2 or area > 0.02 * h * w:
                continue
            short = max(1, min(bw, bh))
            long = max(bw, bh)
            elongation = long / short
            fill = area / max(1, bw * bh)
            if elongation < 2.0 and area > 8:
                continue
            if fill > 0.85 and area > 10:
                continue
            label[comps == comp_id] = cls_id
    return label


def colorize_mask(mask: np.ndarray) -> np.ndarray:
    return PALETTE[np.clip(mask, 0, len(PALETTE) - 1)]


class LaneDataset(Dataset):
    def __init__(self, samples: List[Sample], cfg: dict, split: str):
        self.samples = samples
        self.image_size = int(cfg["dataset"].get("image_size", 256))
        self.road_label = int(cfg["dataset"].get("road_label", 0))
        self.split = split

    def __len__(self):
        return len(self.samples)

    def _augment(self, image: Image.Image, semantic: Image.Image):
        if self.split != "train":
            return image, semantic
        if random.random() < 0.5:
            image = TF.hflip(image)
            semantic = TF.hflip(semantic)
        if random.random() < 0.7:
            image = TF.adjust_brightness(image, random.uniform(0.85, 1.15))
            image = TF.adjust_contrast(image, random.uniform(0.85, 1.20))
            image = TF.adjust_saturation(image, random.uniform(0.85, 1.20))
        return image, semantic

    def __getitem__(self, idx):
        sample = self.samples[idx]
        image = Image.open(sample.image_path).convert("RGB")
        semantic = Image.open(sample.semantic_path).convert("L")
        image, semantic = self._augment(image, semantic)
        image = TF.resize(image, [self.image_size, self.image_size], interpolation=TF.InterpolationMode.BILINEAR)
        semantic = TF.resize(semantic, [self.image_size, self.image_size], interpolation=TF.InterpolationMode.NEAREST)

        rgb = np.array(image, dtype=np.uint8)
        sem = np.array(semantic, dtype=np.uint8)
        label = weak_lane_label(rgb, sem, road_label=self.road_label)

        image_t = TF.to_tensor(image)
        image_t = TF.normalize(image_t, mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
        return {
            "image": image_t,
            "label": torch.from_numpy(label.astype(np.int64)).clamp(0, 2),
            "sample_id": sample.sample_id,
            "rgb": torch.from_numpy(rgb).permute(2, 0, 1).float() / 255.0,
        }


def build_model(num_classes: int = 3):
    model = deeplabv3_mobilenet_v3_large(weights=None, weights_backbone=None, num_classes=num_classes)
    return model


def dice_loss(logits: torch.Tensor, target: torch.Tensor, num_classes: int = 3) -> torch.Tensor:
    probs = torch.softmax(logits, dim=1)
    target_oh = F.one_hot(target.clamp(0, num_classes - 1), num_classes=num_classes).permute(0, 3, 1, 2).float()
    # Do not let the dominant background class control the dice term.
    probs_fg = probs[:, 1:]
    target_fg = target_oh[:, 1:]
    inter = (probs_fg * target_fg).sum(dim=(0, 2, 3))
    denom = probs_fg.sum(dim=(0, 2, 3)) + target_fg.sum(dim=(0, 2, 3))
    return 1.0 - ((2.0 * inter + 1.0) / (denom + 1.0)).mean()


def evaluate(model, loader, device, criterion):
    model.eval()
    total_loss = 0.0
    total_seen = 0
    intersection = torch.zeros(3, device=device)
    union = torch.zeros(3, device=device)
    with torch.no_grad():
        for batch in loader:
            image = batch["image"].to(device)
            label = batch["label"].to(device)
            logits = model(image)["out"]
            loss = criterion(logits, label) + 0.5 * dice_loss(logits, label)
            total_loss += float(loss.item()) * image.size(0)
            total_seen += image.size(0)
            pred = logits.argmax(dim=1)
            for cls_id in range(3):
                pred_c = pred == cls_id
                label_c = label == cls_id
                intersection[cls_id] += (pred_c & label_c).sum()
                union[cls_id] += (pred_c | label_c).sum()
    iou = (intersection / union.clamp_min(1)).detach().cpu().numpy()
    miou_fg = float(np.nanmean(iou[1:]))
    return {
        "loss": total_loss / max(1, total_seen),
        "iou_bg": float(iou[0]),
        "iou_yellow": float(iou[1]),
        "iou_white": float(iou[2]),
        "miou_fg": miou_fg,
    }


def save_preview(model, loader, device, output_dir: Path, max_items: int = 12):
    output_dir.mkdir(parents=True, exist_ok=True)
    model.eval()
    saved = 0
    with torch.no_grad():
        for batch in loader:
            image = batch["image"].to(device)
            logits = model(image)["out"]
            pred = logits.argmax(dim=1).detach().cpu().numpy().astype(np.uint8)
            rgb = (batch["rgb"].numpy().transpose(0, 2, 3, 1) * 255).round().astype(np.uint8)
            label = batch["label"].numpy().astype(np.uint8)
            for idx in range(pred.shape[0]):
                pred_vis = colorize_mask(pred[idx])
                label_vis = colorize_mask(label[idx])
                overlay = cv2.addWeighted(rgb[idx], 0.75, pred_vis, 0.25, 0)
                canvas = np.concatenate([rgb[idx], label_vis, pred_vis, overlay], axis=1)
                out_path = output_dir / f"{batch['sample_id'][idx]}.png"
                cv2.imwrite(str(out_path), cv2.cvtColor(canvas, cv2.COLOR_RGB2BGR))
                saved += 1
                if saved >= max_items:
                    return


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--config", required=True)
    parser.add_argument("--exp_name", default=None)
    args = parser.parse_args()

    cfg = load_yaml(args.config)
    exp_name = args.exp_name or cfg.get("experiment", {}).get("name", "lane_marking_segmentation_v18")
    root = Path(cfg["dataset"]["root"])
    train_samples = collect_samples(root, "train", cfg["dataset"]["image_dir"], cfg["dataset"]["semantic_dir"])
    val_samples = collect_samples(root, "val", cfg["dataset"]["image_dir"], cfg["dataset"]["semantic_dir"])

    seed = int(cfg["training"].get("seed", 42))
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)

    train_ds = LaneDataset(train_samples, cfg, "train")
    val_ds = LaneDataset(val_samples, cfg, "val")
    train_loader = DataLoader(
        train_ds,
        batch_size=int(cfg["training"].get("batch_size", 16)),
        shuffle=True,
        num_workers=int(cfg["training"].get("num_workers", 4)),
        pin_memory=torch.cuda.is_available(),
        persistent_workers=int(cfg["training"].get("num_workers", 4)) > 0,
    )
    val_loader = DataLoader(
        val_ds,
        batch_size=int(cfg["training"].get("batch_size", 16)),
        shuffle=False,
        num_workers=int(cfg["training"].get("num_workers", 4)),
        pin_memory=torch.cuda.is_available(),
        persistent_workers=int(cfg["training"].get("num_workers", 4)) > 0,
    )

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model = build_model(num_classes=3).to(device)
    class_weights = torch.tensor(cfg["training"].get("class_weights", [0.05, 5.0, 2.5]), dtype=torch.float32, device=device)
    criterion = nn.CrossEntropyLoss(weight=class_weights)
    optimizer = torch.optim.AdamW(model.parameters(), lr=float(cfg["training"].get("lr", 2e-4)), weight_decay=float(cfg["training"].get("weight_decay", 1e-4)))
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
        optimizer,
        T_max=int(cfg["training"].get("epochs", 20)),
        eta_min=float(cfg["training"].get("min_lr", 1e-6)),
    )
    use_amp = bool(cfg["training"].get("use_amp", True)) and device.type == "cuda"
    scaler = torch.amp.GradScaler("cuda", enabled=use_amp)

    ckpt_dir = Path(cfg["paths"].get("checkpoint_dir", f"checkpoints/{exp_name}"))
    out_dir = Path(cfg["paths"].get("output_dir", f"outputs/{exp_name}"))
    ckpt_dir.mkdir(parents=True, exist_ok=True)
    out_dir.mkdir(parents=True, exist_ok=True)

    print(f"[Lane v18] exp={exp_name}", flush=True)
    print(f"[Lane v18] train={len(train_ds)} val={len(val_ds)} device={device}", flush=True)
    best_score = -1.0
    metrics = []
    start = time.time()
    for epoch in range(1, int(cfg["training"].get("epochs", 20)) + 1):
        model.train()
        running = 0.0
        seen = 0
        for step, batch in enumerate(train_loader):
            image = batch["image"].to(device, non_blocking=True)
            label = batch["label"].to(device, non_blocking=True)
            optimizer.zero_grad(set_to_none=True)
            with torch.autocast("cuda", dtype=torch.float16, enabled=use_amp):
                logits = model(image)["out"]
                loss = criterion(logits, label) + 0.5 * dice_loss(logits, label)
            scaler.scale(loss).backward()
            scaler.step(optimizer)
            scaler.update()
            running += float(loss.item()) * image.size(0)
            seen += image.size(0)
            if step % int(cfg["training"].get("log_interval", 50)) == 0:
                print(f"[Train] epoch={epoch} step={step}/{len(train_loader)} loss={running / max(1, seen):.4f}", flush=True)
        scheduler.step()
        val_metrics = evaluate(model, val_loader, device, criterion)
        val_metrics["epoch"] = epoch
        metrics.append(val_metrics)
        score = val_metrics["miou_fg"]
        print(
            "[Val] "
            f"epoch={epoch} loss={val_metrics['loss']:.4f} "
            f"yellow_iou={val_metrics['iou_yellow']:.4f} "
            f"white_iou={val_metrics['iou_white']:.4f} "
            f"fg_mIoU={val_metrics['miou_fg']:.4f}",
            flush=True,
        )

        state = {
            "epoch": epoch,
            "model_state_dict": model.state_dict(),
            "optimizer_state_dict": optimizer.state_dict(),
            "metrics": val_metrics,
            "config": cfg,
        }
        torch.save(state, ckpt_dir / "latest.pth")
        if score > best_score:
            best_score = score
            torch.save(state, ckpt_dir / "best.pth")
            print(f"[Checkpoint] new best fg_mIoU={best_score:.4f}", flush=True)
        if epoch % int(cfg["training"].get("preview_interval", 5)) == 0 or epoch == 1:
            save_preview(model, val_loader, device, out_dir / "previews" / f"epoch_{epoch:03d}", max_items=int(cfg["training"].get("preview_count", 12)))

    with open(out_dir / "metrics.json", "w", encoding="utf-8") as f:
        json.dump({"best_fg_mIoU": best_score, "history": metrics}, f, indent=2)
    save_preview(model, val_loader, device, out_dir / "previews" / "final", max_items=int(cfg["training"].get("preview_count", 12)))
    print(f"[Done] best_fg_mIoU={best_score:.4f}", flush=True)
    print(f"[Done] checkpoint={ckpt_dir / 'best.pth'}", flush=True)
    print(f"[Done] elapsed_hours={(time.time() - start) / 3600:.2f}", flush=True)


if __name__ == "__main__":
    main()
